services:
  app:
    build: .
    container_name: lms-app
    #depends_on:
    #  mysql:
    #    condition: service_healthy
    environment:
      DB_URL: ${DB_URL:?DB_URL is required}
      DB_USERNAME: ${DB_USERNAME:?DB_USERNAME is required}
      #DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:?SPRING_PROFILES_ACTIVE is required}
      APP_STORAGE_LOCAL_ROOT: ${APP_STORAGE_LOCAL_ROOT-}
      APP_STORAGE_S3_BUCKET: ${APP_STORAGE_S3_BUCKET-}
      APP_STORAGE_S3_REGION: ${APP_STORAGE_S3_REGION-}
      APP_STORAGE_S3_PREFIX: ${APP_STORAGE_S3_PREFIX-}
    ports:
      - "${APP_PORT:?APP_PORT is required}:8080"
    volumes:
      - upload-data:/app/uploads

volumes:
  upload-data: